### ISSUE TITLE
process audio buffer in byte

### ISSUE THREAD

**Issue by neo1949** [ideastudios/Vad#1]
library 中 `processBuffer（int sampleRate, short[] audioData, int dataLength）` 封装的是 `short[]` 类型的数据，现在需要处理 `byte[]` 类型的音频数据，请问添加新的 jni 接口并编译 .so 库？

**Comment by ideastudios** [comment]
https://github.com/ideastudios/IdealRecorder/blob/master/library/src/main/java/tech/oom/idealrecorder/utils/BytesTransUtil.java 看看这个 可以转换的

**Comment by neo1949** [comment]
> https://github.com/ideastudios/IdealRecorder/blob/master/library/src/main/java/tech/oom/idealrecorder/utils/BytesTransUtil.java 看看这个 可以转换的

我知道有类可以实现转换的，只是想基于你的项目封装一个新的接口，快速学习一下如何封装 jni 编译 .so 库：
```java
short[] wrapData = new short[mMinBufferSize / 2];
ByteBuffer.wrap(audioBuffer).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(wrapData);
```
目前，先基于已有的接口开发测试吧，感谢提供的封装。
